"""DocumentEmbedder, embedding of the final document markdown.
Conversion of metadata/embedding_metadata.py: logic MOVED as-is,
the call is now made asynchronously via embeddings.get_embedding.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING

from ..clients.openai_client import embedding_to_string

if TYPE_CHECKING:
    from ..clients.base import AsyncEmbeddingClient
    from ..workspace import DocumentWorkspace

_log = logging.getLogger(__name__)


def read_embed_markdown(workspace: DocumentWorkspace) -> str:
    """
    Reads the final markdown for a given document.

    Prefers <doc>_final_embed.md (Markdown tables replaced with JSONL,
    generated by markdown_tables_to_jsonl.py --embed-output) if it exists,
    otherwise, uses <doc>_final.md. 
    Backward compatible: documents without_final_embed.md 
    (v1/v2/baseline) are handled unchanged.
    """
    for candidate in (workspace.final_embed_markdown, workspace.final_markdown):
        if candidate.exists():
            return candidate.read_text(encoding="utf-8")
    return ""


def write_embedding_output(workspace: DocumentWorkspace, embedding: list[float]) -> Path:
    """Writes the raw vector to metadata/embedding.json (same format)."""
    workspace.metadata_dir.mkdir(parents=True, exist_ok=True)
    workspace.embedding_json.write_text(
        json.dumps(embedding, ensure_ascii=False), encoding="utf-8"
    )
    return workspace.metadata_dir


class DocumentEmbedder:
    """Generates and writes the embedding for the final markdown, asynchronous contract."""

    def __init__(self, embeddings: AsyncEmbeddingClient, embedding_model_name: str) -> None:
        self._embeddings = embeddings
        self.embedding_model_name = embedding_model_name

    async def run(self, workspace: DocumentWorkspace) -> tuple[str, str]:
        """Equivalent to run_embedding: reads the markdown, generates the embedding,
        writes embedding.json, and returns (embedding_string, embedding_model_name)."""
        markdown_content = read_embed_markdown(workspace)
        if not markdown_content:
            raise FileNotFoundError(
                f"No markdown file found for '{workspace.doc_name}' "
                f"in {workspace.root.parent}"
            )

        _log.info("Embedding generation")
        embedding = await self._embeddings.get_embedding(markdown_content)

        out_dir = write_embedding_output(workspace, embedding)
        _log.info("Embedding written to : %s", out_dir / "embedding.json")

        return embedding_to_string(embedding), self.embedding_model_name
