"""DocumentWorkspace centralizes all document path resolution logic.

This class centralizes the generation of document paths and names.
It replaces the 44 resolve_* functions as well as the document naming f-strings scattered throughout the codebase.

The generated names form a contract with the existing pipeline: they must match the names actually produced by it. 
The reference is the state observed on disk and the conventions already used in the code, not this documentation.

Document names may contain accents, spaces, and typographic apostrophes (e.g. Cas de sortie - Prolongation d'adhésion).
No normalization or cleaning is performed by this class, except for the strip() applied to the stem in for_document.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .settings import Settings


@dataclass(frozen=True)
class DocumentWorkspace:
    """Input/output paths of a document processed by the pipeline."""

    doc_name: str
    source_pdf: Path
    root: Path
    # Document folder RELATIVE to input_files/ (e.g. Path("afac/Adhésion")).
    # Populated from batch 2 onwards, consumed by root only in batch F1:
    # for_document() computes it, while root ignores it.

    relative_dir: Path = field(default_factory=lambda: Path())

    # All doctags output paths 
    @property
    def doctags(self) -> Path:
        return self.root / f"{self.doc_name}.doctags"

    @property
    def reordered_doctags(self) -> Path:
        return self.root / f"{self.doc_name}_reordered.doctags"

    @property
    def reordered_with_tables_doctags(self) -> Path:
        return self.root / f"{self.doc_name}_reordered_with_tables.doctags"

    @property
    def reordered_with_tables_pictures_doctags(self) -> Path:
        return self.root / f"{self.doc_name}_reordered_with_tables_pictures.doctags"

    @property
    def url_vlm_doctags(self) -> Path:
        return self.root / f"{self.doc_name}_url_vlm.doctags"

    # All markdown output paths
    @property
    def markdown(self) -> Path:
        return self.root / f"{self.doc_name}.md"

    @property
    def url_vlm_markdown(self) -> Path:
        return self.root / f"{self.doc_name}_url_vlm.md"

    @property
    def vlm_check_markdown(self) -> Path:
        return self.root / f"{self.doc_name}_vlm_check.md"

    @property
    def image_descriptions(self) -> Path:
        return self.root / f"{self.doc_name}_image_descriptions.md"

    @property
    def final_markdown(self) -> Path:
        return self.root / f"{self.doc_name}_final.md"

    @property
    def final_embed_markdown(self) -> Path:
        # Generated by markdown_tables_to_jsonl.py (an OUT-OF-pipeline tool,
        # used for comparison testing between Markdown tables and JSONL tables).
        # Not part of the official pipeline.
        return self.root / f"{self.doc_name}_final_embed.md"

    # Data at the document root
    @property
    def docling_json(self) -> Path:
        # Read by load_input_json (script: metadata_generation).
        return self.root / f"{self.doc_name}.json"

    @property
    def text_dump(self) -> Path:
        return self.root / f"{self.doc_name}.txt"

    @property
    def hyperlinks_jsonl(self) -> Path:
        return self.root / f"hyperlinks_data_{self.doc_name}.jsonl"

    # Other useful subflders
    @property
    def used_images_dir(self) -> Path:
        return self.root / "used_images"

    @property
    def tables_dir(self) -> Path:
        return self.root / "tables"

    @property
    def metadata_dir(self) -> Path:
        return self.root / "metadata"

    @property
    def opencv_validation_dir(self) -> Path:
        # Visual QA (opencv-check step, disabled by default) — identified
        # in opencv_checker.resolve_output, absent from the reference freeze
        # precisely because the step was skipped there.
        return self.root / "opencv_validation"

    # contents of metadata/ subfolder within the document root output folder
    @property
    def final_csv(self) -> Path:
        # in metadata/, NOT at the document root.
        return self.metadata_dir / f"{self.doc_name}_final.csv"

    @property
    def resume_markdown(self) -> Path:
        return self.metadata_dir / "resume.md"

    @property
    def intent_json(self) -> Path:
        return self.metadata_dir / "intent.json"

    @property
    def hyq_json(self) -> Path:
        return self.metadata_dir / "hyq.json"

    @property
    def embedding_json(self) -> Path:
        return self.metadata_dir / "embedding.json"

    @property
    def hyq_dir(self) -> Path:
        return self.metadata_dir / f"hyq_{self.doc_name}"

    def ensure_dirs(self) -> None:
        """Create root/ and its standard subfolders if they are missing."""
        for directory in (self.root, self.used_images_dir, self.tables_dir, self.metadata_dir):
            directory.mkdir(parents=True, exist_ok=True)

    @classmethod
    def for_document(cls, pdf: Path, settings: Settings) -> DocumentWorkspace:
        """Builds the workspace for a PDF. 
        Since batch F1, the output **reproduces the input directory structure**: 
        ``input_files/afac/Adhésion/x.pdf`` produces 
        ``output_files_preprocessing/afac/Adhésion/x/``. 
        The file names inside remain unchanged. 
        This is what fixes the silent overwrite of two documents with the same name stored in different folders 
        (the flat layout gave them the same ``root``). 
        ``relative_dir`` is ``Path(".")`` for a document outside ``input_files/`` 
        the output then remains at the root, as before.
        """
        pdf = Path(pdf)
        doc_name = pdf.stem.strip()
        try:
            relative_dir = pdf.resolve().relative_to(
                settings.input_files_root.resolve()
            ).parent
        except ValueError:
            relative_dir = Path()
        root = settings.output_files_root / relative_dir / doc_name
        return cls(
            doc_name=doc_name,
            source_pdf=pdf,
            root=root,
            relative_dir=relative_dir,
        )
